"""initial_tables

Revision ID: 6bcabf90b64c
Revises: 
Create Date: 2026-03-16 13:56:20.150705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bcabf90b64c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('child_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('reading_level', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_profiles_id'), 'child_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_child_profiles_parent_id'), 'child_profiles', ['parent_id'], unique=False)
    op.create_table('parent_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('blocked_topics', sa.JSON(), nullable=True),
    sa.Column('preferred_themes', sa.JSON(), nullable=True),
    sa.Column('daily_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_settings_id'), 'parent_settings', ['id'], unique=False)
    op.create_index(op.f('ix_parent_settings_parent_id'), 'parent_settings', ['parent_id'], unique=True)
    op.create_table('growth_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('behavior_tags', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_reports_child_id'), 'growth_reports', ['child_id'], unique=False)
    op.create_index(op.f('ix_growth_reports_id'), 'growth_reports', ['id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('theme', sa.String(length=100), nullable=False),
    sa.Column('main_character', sa.String(length=100), nullable=False),
    sa.Column('scene', sa.String(length=100), nullable=False),
    sa.Column('story_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_child_id'), 'stories', ['child_id'], unique=False)
    op.create_index(op.f('ix_stories_id'), 'stories', ['id'], unique=False)
    op.create_table('story_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('current_scene_index', sa.Integer(), nullable=True),
    sa.Column('story_state_json', sa.JSON(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child_profiles.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_sessions_child_id'), 'story_sessions', ['child_id'], unique=False)
    op.create_index(op.f('ix_story_sessions_id'), 'story_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_story_sessions_story_id'), 'story_sessions', ['story_id'], unique=False)
    op.create_table('safety_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('scene_index', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('audit_result', sa.String(length=50), nullable=False),
    sa.Column('risk_type', sa.String(length=100), nullable=True),
    sa.Column('revised_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['story_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_audit_logs_id'), 'safety_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_safety_audit_logs_session_id'), 'safety_audit_logs', ['session_id'], unique=False)
    op.create_table('story_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('scene_index', sa.Integer(), nullable=False),
    sa.Column('option_key', sa.String(length=10), nullable=False),
    sa.Column('option_text', sa.String(length=500), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['story_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_choices_id'), 'story_choices', ['id'], unique=False)
    op.create_index(op.f('ix_story_choices_session_id'), 'story_choices', ['session_id'], unique=False)
    op.create_table('story_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['story_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_messages_id'), 'story_messages', ['id'], unique=False)
    op.create_index(op.f('ix_story_messages_session_id'), 'story_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_messages_session_id'), table_name='story_messages')
    op.drop_index(op.f('ix_story_messages_id'), table_name='story_messages')
    op.drop_table('story_messages')
    op.drop_index(op.f('ix_story_choices_session_id'), table_name='story_choices')
    op.drop_index(op.f('ix_story_choices_id'), table_name='story_choices')
    op.drop_table('story_choices')
    op.drop_index(op.f('ix_safety_audit_logs_session_id'), table_name='safety_audit_logs')
    op.drop_index(op.f('ix_safety_audit_logs_id'), table_name='safety_audit_logs')
    op.drop_table('safety_audit_logs')
    op.drop_index(op.f('ix_story_sessions_story_id'), table_name='story_sessions')
    op.drop_index(op.f('ix_story_sessions_id'), table_name='story_sessions')
    op.drop_index(op.f('ix_story_sessions_child_id'), table_name='story_sessions')
    op.drop_table('story_sessions')
    op.drop_index(op.f('ix_stories_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_child_id'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_growth_reports_id'), table_name='growth_reports')
    op.drop_index(op.f('ix_growth_reports_child_id'), table_name='growth_reports')
    op.drop_table('growth_reports')
    op.drop_index(op.f('ix_parent_settings_parent_id'), table_name='parent_settings')
    op.drop_index(op.f('ix_parent_settings_id'), table_name='parent_settings')
    op.drop_table('parent_settings')
    op.drop_index(op.f('ix_child_profiles_parent_id'), table_name='child_profiles')
    op.drop_index(op.f('ix_child_profiles_id'), table_name='child_profiles')
    op.drop_table('child_profiles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
